### ISSUE TITLE
 python exp_s3_call_peaks.py 

### ISSUE THREAD

**Issue by molsim** [ncbi/HYDROID#3]
(venv) parallels@parallels-vm:~/example2$ python exp_s3_call_peaks.py 
/home/parallels/venv/local/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
=======Invoking peak identification algorithm======
Peaks identified:  64
===============
Traceback (most recent call last):
  File "exp_s3_call_peaks.py", line 48, in <module>
    call_peaks_interactive(lane_profile_file,lane_config_file,DNAseq=s['seq'],labeled_end=s['label'],lane_name=s['footprinting_profile'],helper_prof_names=s['helper_profiles'])
  File "/home/parallels/venv/local/lib/python2.7/site-packages/hydroid/HYDROIDexp.py", line 372, in call_peaks_interactive
    helper_lanes_orig_array[l]=helper_lanes[l][~np.isnan(lane)].values
  File "/home/parallels/venv/local/lib/python2.7/site-packages/pandas/core/series.py", line 664, in __getitem__
    return self._get_with(key)
  File "/home/parallels/venv/local/lib/python2.7/site-packages/pandas/core/series.py", line 700, in _get_with
    return self._get_values(key)
  File "/home/parallels/venv/local/lib/python2.7/site-packages/pandas/core/series.py", line 734, in _get_values
    return self._values[indexer]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2657 but corresponding boolean dimension is 2634

**Comment by mtkilic** [comment]
I think in your `HYDROIDexp.py` file in line 372, if you index 0 instead of 1 it might work.
